{{ config(materialized='table') }}

SELECT avg(ATTENDANCE_PERCENT) AVG_ATTENDANCE_PERCENT, 
avg(TO_DOUBLE(replace(ABSENT_PERCENT, 'NA', 0))) AVG_ABSENT_PERCENT, 
avg(TO_DOUBLE(replace(COVID_COUNTY_PERCENT_INCREASE, 'NA', 0))) AVG_COVID_COUNTY_PERCENT_INCREASE, 
avg(TO_DOUBLE(replace(COVID_STATE_PERCENT_INCREASE, 'NA', 0))) AVG_COVID_STATE_PERCENT_INCREASE,
DISTRICT, COUNTY 
FROM "FIVETRAN_DATABASE"."ATTENDANCE"."GRADE_LEVEL"
GROUP BY DISTRICT, COUNTY

