{{ config(materialized='view') }}

with source_data as 
(SELECT avg(TO_DOUBLE(replace(ATTENDANCE_PERCENT, 'NA', 0))) AVG_ATTENDANCE_PERCENT, 
avg(TO_DOUBLE(replace(ABSENT_PERCENT, 'NA', 0))) AVG_ABSENT_PERCENT, 
avg(TO_DOUBLE(replace(COVID_COUNTY_PERCENT_INCREASE, 'NA', 0))) AVG_COVID_COUNTY_PERCENT_INCREASE, 
avg(TO_DOUBLE(replace(COVID_STATE_PERCENT_INCREASE, 'NA', 0))) AVG_COVID_STATE_PERCENT_INCREASE,
DISTRICT, COUNTY 
FROM {{ source('fivetran_sf', 'GRADE_LEVEL_P') }}
GROUP BY DISTRICT, COUNTY)

SELECT * FROM source_data
