{{ config(materialized='view') }}

with source_data as (SELECT avg(ATTENDANCE_PERCENT) AVG_ATTENDANCE_PERCENT, 
avg(TO_DOUBLE(replace(ABSENT_PERCENT, 'NA', 0))) AVG_ABSENT_PERCENT, 
avg(TO_DOUBLE(replace(COVID_COUNTY_PERCENT_INCREASE, 'NA', 0))) AVG_COVID_COUNTY_PERCENT_INCREASE, 
avg(TO_DOUBLE(replace(COVID_STATE_PERCENT_INCREASE, 'NA', 0))) AVG_COVID_STATE_PERCENT_INCREASE,
DISTRICT, COUNTY 
FROM {{ source('fivetran_sf', 'GRADE_LEVEL') }}
GROUP BY DISTRICT, COUNTY)

SEELCT * FROM source_data

