
version: 2

sources:
  - name: fivetran_sf
    database: FIVETRAN_DATABASE
    schema: ATTENDANCE
    tables:
      - name: GRADE_LEVEL

models:
    - name: grade_level_analysis
      description: "Analyzed view"
