
version: 2

sources:
  - name: fivetran_sf
    database: FIVETRAN_DATABASE
    schema: POSTGRES_GOOGLE_SHEETS
    tables:
      - name: GRADE_LEVEL_P

models:
    - name: grade_level_analysis
      description: "Analyzed view"
